CREATE DATABASE IF NOT EXISTS Event_db;
USE Event_db;

CREATE TABLE IF NOT EXISTS Users(
	UserID int NOT NULL AUTO_INCREMENT,
    Firstname VARCHAR(50) NOT NULL,
    Lastname VARCHAR(50) NOT NULL,
    Username VARCHAR(50) NOT NULL,
	Password VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    PRIMARY KEY (UserID)
);

CREATE TABLE IF NOT EXISTS EventTBL(
	EventID INT NOT NULL AUTO_INCREMENT,
    UserID INT NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Description TEXT NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Location VARCHAR(100) NOT NULL,
    Date DATE NOT NULL,
    MaxSeat INT DEFAULT 10,
    Amount DECIMAL(6, 2) NOT NULL,
    PRIMARY KEY (EventID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Book(
	BookID INT NOT NULL AUTO_INCREMENT,
    EventID INT NOT NULL,
    UserID INT NOT NULL,
    PRIMARY KEY (BookID),
	FOREIGN KEY (EventID) REFERENCES EventTBL(EventID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    UNIQUE (EventID, UserID)
);